import { User } from './users.types'

export const userList: User[] = [
    {
        _id: '65e6debb0fe62a45b8f3d5c6',
        username: 'HubbardGross',
        firstName: 'Claire',
        lastName: 'Dean',
        lastName2: 'Pitts',
        email: 'clairepitts@polaria.com',
        phone: '+34 (856) 521-2959',
        userStatus: 'online',
        identification: {
            value: '65e6debb3c19f27fd878586f',
            type: 'NIF',
        },
        picture: 'http://placehold.it/32x32',
    },
    {
        _id: '65e6debb77051c4ca2bb45f6',
        username: 'BrooksRosetta',
        firstName: 'Fuentes',
        lastName: 'Marquez',
        lastName2: 'Johnston',
        email: 'fuentesjohnston@polaria.com',
        phone: '+34 (926) 485-2598',
        userStatus: 'online',
        identification: {
            value: '65e6debb2cf9b60fbbc755b5',
            type: 'NIF',
        },
        picture: 'http://placehold.it/32x32',
    },
    {
        _id: '65e6debb3e8b19d61f1ca096',
        username: 'MorrisGonzalez',
        firstName: 'Olive',
        lastName: 'Manning',
        lastName2: 'Holt',
        email: 'oliveholt@polaria.com',
        phone: '+34 (880) 453-2417',
        userStatus: 'online',
        identification: {
            value: '65e6debbe0c5e536e66e9937',
            type: 'DNI',
        },
        picture: 'http://placehold.it/32x32',
    },
    {
        _id: '65e6debb3b80d9d5f8f06c3b',
        username: 'KellyCristina',
        firstName: 'Walls',
        lastName: 'Holman',
        lastName2: 'Perry',
        email: 'wallsperry@polaria.com',
        phone: '+34 (859) 590-3891',
        userStatus: 'online',
        identification: {
            value: '65e6debb1651a7bc3b41d742',
            type: 'DNI',
        },
        picture: 'http://placehold.it/32x32',
    },
    {
        _id: '65e6debbbc000f1b7e32dd86',
        username: 'SosaMarlene',
        firstName: 'Miles',
        lastName: 'Lynch',
        lastName2: 'Lowery',
        email: 'mileslowery@polaria.com',
        phone: '+34 (938) 420-2197',
        userStatus: 'busy',
        identification: {
            value: '65e6debb0ef9856df8be697e',
            type: 'DNI',
        },
        picture: 'http://placehold.it/32x32',
    },
    {
        _id: '65e6debbc8e2913b4e4ad305',
        username: 'AyalaGamble',
        firstName: 'Moreno',
        lastName: 'Harrell',
        lastName2: 'Mcgee',
        email: 'morenomcgee@polaria.com',
        phone: '+34 (946) 556-2401',
        userStatus: 'away',
        identification: {
            value: '65e6debb4932411d3c5baea2',
            type: 'NIF',
        },
        picture: 'http://placehold.it/32x32',
    },
    {
        _id: '65e6debb224132aeca64f6e0',
        username: 'LangBass',
        firstName: 'Molly',
        lastName: 'Middleton',
        lastName2: 'Mccarthy',
        email: 'mollymccarthy@polaria.com',
        phone: '+34 (988) 462-3365',
        userStatus: 'busy',
        identification: {
            value: '65e6debbe86dc45da2018922',
            type: 'DNI',
        },
        picture: 'http://placehold.it/32x32',
    },
    {
        _id: '65e6debbef63e197b666079f',
        username: 'BowersSolis',
        firstName: 'Thomas',
        lastName: 'Huff',
        lastName2: 'Odom',
        email: 'thomasodom@polaria.com',
        phone: '+34 (835) 492-3574',
        userStatus: 'offline',
        identification: {
            value: '65e6debbb4da63448e03dae3',
            type: 'NIF',
        },
        picture: 'http://placehold.it/32x32',
    },
    {
        _id: '65e6debbde3b34a8c4f18e4a',
        username: 'GriffinReese',
        firstName: 'Rosa',
        lastName: 'Maldonado',
        lastName2: 'Orr',
        email: 'rosaorr@polaria.com',
        phone: '+34 (995) 551-2258',
        userStatus: 'offline',
        identification: {
            value: '65e6debb52120a1d20c46995',
            type: 'DNI',
        },
        picture: 'http://placehold.it/32x32',
    },
    {
        _id: '65e6debb1d825abded5a62eb',
        username: 'CooleyLester',
        firstName: 'Mcfadden',
        lastName: 'Vaughn',
        lastName2: 'Finley',
        email: 'mcfaddenfinley@polaria.com',
        phone: '+34 (946) 489-3739',
        userStatus: 'offline',
        identification: {
            value: '65e6debbe88a8336ec6ca5d6',
            type: 'DNI',
        },
        picture: 'http://placehold.it/32x32',
    },
]
