import { Friend } from './friends.types'

export const friendList: Friend[] = [
    {
        _id: '65e57c7c946ac93043e7351c',
        picture: 'http://placehold.it/32x32',
        age: 33,
        eyeColor: 'green',
        name: 'Munoz Key',
        email: 'munozkey@conjurica.com',
        phone: '+1 (847) 557-3320',
        address: '674 Hinsdale Street, Biddle, District Of Columbia, 9497',
        about: 'Incididunt pariatur Lorem in eiusmod eiusmod consequat. Veniam sit reprehenderit elit cillum labore occaecat tempor. Sint fugiat cupidatat occaecat proident nulla aliqua labore id voluptate qui ut sit. Irure mollit anim enim fugiat officia sunt aliqua officia.\r\n',
        favoriteFruit: 'banana',
    },
    {
        _id: '65e57c7cfc9ff5b941b3c833',
        picture: 'http://placehold.it/32x32',
        age: 22,
        eyeColor: 'green',
        name: 'Diane Parks',
        email: 'dianeparks@conjurica.com',
        phone: '+1 (977) 502-2030',
        address: '605 Kings Place, Steinhatchee, New York, 2270',
        about: 'Est incididunt et laboris fugiat non fugiat duis reprehenderit. Anim laboris enim id laborum pariatur magna. Ullamco aute deserunt ut laborum nostrud voluptate.\r\n',
        favoriteFruit: 'banana',
    },
    {
        _id: '65e57c7c5b4f35dfa79e3d2b',
        picture: 'http://placehold.it/32x32',
        age: 36,
        eyeColor: 'blue',
        name: 'Mooney Nash',
        email: 'mooneynash@conjurica.com',
        phone: '+1 (806) 425-3971',
        address: '272 Willmohr Street, Fairacres, Vermont, 5961',
        about: 'Ut aliquip cupidatat enim duis elit pariatur ipsum tempor id mollit. Pariatur et deserunt dolor pariatur laborum exercitation est excepteur labore non in aute ex ut. Duis amet minim occaecat magna consequat officia pariatur cillum et aliquip amet cupidatat consequat do. Amet esse ut minim deserunt cillum cillum aliquip consectetur velit. Dolor esse voluptate amet cupidatat laborum.\r\n',
        favoriteFruit: 'apple',
    },
    {
        _id: '65e57c7cad7c7e04dda59c69',
        picture: 'http://placehold.it/32x32',
        age: 34,
        eyeColor: 'green',
        name: 'Felicia Clark',
        email: 'feliciaclark@conjurica.com',
        phone: '+1 (970) 501-3109',
        address: '709 Prescott Place, Russellville, Alabama, 5411',
        about: 'Mollit labore reprehenderit officia in in irure mollit nostrud et proident minim veniam culpa dolore. Id incididunt proident ad dolor ullamco eiusmod aliqua nulla. Dolore in ipsum ullamco excepteur eiusmod deserunt.\r\n',
        favoriteFruit: 'apple',
    },
    {
        _id: '65e57c7c3b9b6681440fd0b1',
        picture: 'http://placehold.it/32x32',
        age: 25,
        eyeColor: 'blue',
        name: 'Mack Le',
        email: 'mackle@conjurica.com',
        phone: '+1 (801) 560-3898',
        address: '627 Butler Street, Bowmansville, Michigan, 9461',
        about: 'Ea fugiat ad cupidatat aute cupidatat voluptate non enim est. Est mollit consequat veniam enim dolor pariatur amet consequat velit. Adipisicing elit adipisicing magna consectetur nisi magna magna. Commodo qui sit est est id excepteur id. Et Lorem voluptate fugiat esse dolore. Dolor nulla ea consectetur ea aliqua sit et elit mollit eiusmod.\r\n',
        favoriteFruit: 'strawberry',
    },
    {
        _id: '65e57c7c4a92a90ec2e74031',
        picture: 'http://placehold.it/32x32',
        age: 31,
        eyeColor: 'green',
        name: 'Carrillo Banks',
        email: 'carrillobanks@conjurica.com',
        phone: '+1 (908) 568-2772',
        address: '287 Lee Avenue, Eden, Hawaii, 4112',
        about: 'Ex consequat voluptate cupidatat est exercitation irure ex amet duis exercitation pariatur sunt tempor culpa. Ea ut deserunt duis non laborum labore labore qui quis excepteur eiusmod occaecat eiusmod nostrud. Et occaecat elit est eu. Est laborum ut aliqua reprehenderit eu ut irure cupidatat ipsum. Tempor ad et Lorem officia Lorem est Lorem ullamco adipisicing irure dolore ipsum culpa velit. In aliquip pariatur aliqua est eiusmod incididunt nostrud eiusmod et culpa. Ut eiusmod amet sint aliquip elit nulla incididunt eiusmod.\r\n',
        favoriteFruit: 'banana',
    },
    {
        _id: '65e57c7cd4efe10d2262a4ee',
        picture: 'http://placehold.it/32x32',
        age: 38,
        eyeColor: 'green',
        name: 'Angelia Cross',
        email: 'angeliacross@conjurica.com',
        phone: '+1 (949) 579-3960',
        address: '901 Micieli Place, Drytown, Arizona, 5223',
        about: 'Ex aliqua amet nostrud eu aliqua consectetur ullamco cupidatat ipsum ad minim reprehenderit veniam voluptate. Incididunt culpa elit ad id ad dolor. Aliquip excepteur irure aute sit. Cillum ex anim laboris duis. Elit Lorem cupidatat ad qui proident Lorem sunt exercitation non et labore laboris officia. Consequat pariatur sit esse nulla consectetur non excepteur consequat nulla ea deserunt ipsum cillum excepteur.\r\n',
        favoriteFruit: 'banana',
    },
    {
        _id: '65e57c7cd1f3d1d6920c4374',
        picture: 'http://placehold.it/32x32',
        age: 26,
        eyeColor: 'blue',
        name: 'Kennedy Mercer',
        email: 'kennedymercer@conjurica.com',
        phone: '+1 (800) 467-3775',
        address: '308 Schaefer Street, Henrietta, Massachusetts, 793',
        about: 'Veniam eiusmod qui exercitation aute commodo. Do laborum esse dolor aliquip esse eu mollit aliquip dolore esse sit voluptate. Ad Lorem aliquip elit duis in dolor reprehenderit anim adipisicing adipisicing pariatur reprehenderit eiusmod id. Eu magna culpa non pariatur fugiat minim ad enim non velit est esse dolore. Cupidatat irure ad quis minim reprehenderit est mollit adipisicing eiusmod reprehenderit. Reprehenderit magna occaecat eiusmod enim sunt quis magna consequat consectetur. Enim mollit cillum in aliquip id irure commodo magna.\r\n',
        favoriteFruit: 'banana',
    },
    {
        _id: '65e57c7c3adadde1b1a5d594',
        picture: 'http://placehold.it/32x32',
        age: 27,
        eyeColor: 'green',
        name: 'James Cook',
        email: 'jamescook@conjurica.com',
        phone: '+1 (954) 468-2927',
        address: '518 Kenmore Terrace, Fredericktown, Iowa, 4217',
        about: 'Ea anim ut aliquip anim Lorem amet ad laborum. Eiusmod ad reprehenderit tempor consectetur eu eiusmod id nisi veniam. Commodo dolore aute quis pariatur aliqua officia enim. Nulla ipsum aliquip enim commodo in cillum consectetur qui anim fugiat fugiat veniam.\r\n',
        favoriteFruit: 'apple',
    },
    {
        _id: '65e57c7c5a85cf0a0e352af7',
        picture: 'http://placehold.it/32x32',
        age: 22,
        eyeColor: 'blue',
        name: 'Gardner Everett',
        email: 'gardnereverett@conjurica.com',
        phone: '+1 (800) 404-3682',
        address: '123 Roosevelt Court, Adamstown, Texas, 4936',
        about: 'Culpa veniam veniam dolore do veniam do culpa magna sit ea deserunt enim mollit ut. Irure ipsum cillum commodo duis. Pariatur ad ex sint amet in do ea aliquip in nulla.\r\n',
        favoriteFruit: 'strawberry',
    },
    {
        _id: '65e57c7c150f8bf19a19fbe2',
        picture: 'http://placehold.it/32x32',
        age: 40,
        eyeColor: 'brown',
        name: 'Durham Lawson',
        email: 'durhamlawson@conjurica.com',
        phone: '+1 (841) 408-2522',
        address: '285 Jaffray Street, Bynum, Washington, 3156',
        about: 'Ex anim tempor mollit eiusmod et do. Tempor eu qui mollit exercitation nostrud velit sint Lorem esse laborum minim est ullamco tempor. Magna fugiat consequat commodo dolore adipisicing anim elit. Ipsum et enim duis pariatur est anim ipsum nisi ut.\r\n',
        favoriteFruit: 'banana',
    },
    {
        _id: '65e57c7c7fd32dce450b754d',
        picture: 'http://placehold.it/32x32',
        age: 40,
        eyeColor: 'green',
        name: 'Holt Wright',
        email: 'holtwright@conjurica.com',
        phone: '+1 (999) 467-2180',
        address: '455 Provost Street, Makena, Palau, 4578',
        about: 'Laborum magna minim sit culpa culpa sit amet Lorem velit commodo occaecat fugiat ullamco. Culpa veniam velit aliqua est. Deserunt tempor nisi ex nulla cillum labore sit. Ullamco voluptate mollit laborum ullamco irure aute officia aliqua consectetur. Esse enim incididunt tempor ex excepteur deserunt ut amet cupidatat est ipsum mollit eu aliqua. Proident elit deserunt elit occaecat dolor. In velit laboris minim eu cillum nisi.\r\n',
        favoriteFruit: 'banana',
    },
    {
        _id: '65e57c7c8c44c6bbe5af66aa',
        picture: 'http://placehold.it/32x32',
        age: 31,
        eyeColor: 'brown',
        name: 'Keith Terrell',
        email: 'keithterrell@conjurica.com',
        phone: '+1 (951) 400-2515',
        address: '696 Anthony Street, Aberdeen, North Carolina, 4150',
        about: 'Aliqua quis veniam voluptate non dolore aute. Nulla sunt sit minim tempor cupidatat do esse. Incididunt sit sint deserunt duis anim magna incididunt proident anim. Nostrud commodo aliqua amet deserunt. Ullamco nulla minim cillum irure amet Lorem sit commodo aliqua non consequat nostrud. Ex ut tempor id est adipisicing amet proident elit tempor labore in dolore. Elit exercitation adipisicing nostrud nostrud proident ex labore nisi.\r\n',
        favoriteFruit: 'banana',
    },
]
